@TeamManager_HostAddress = http://localhost:5207

### Get all athletes
GET {{TeamManager_HostAddress}}/api/athlete
Accept: application/json

###

### Create new athlete

POST {{TeamManager_HostAddress}}/api/athlete
Content-Type: application/json

{
  "name": "Felipe Renan",
  "age": 19,
  "height": 1.75,
  "weight": 93.5,
  "position": 7
}

###

### Delete athlete
DELETE {{TeamManager_HostAddress}}/api/athlete/2
Content-Type: application/json  

###

### Update athlete

PUT {{TeamManager_HostAddress}}/api/athlete/1
Content-Type: application/json

{
  "id": 1,
  "name": "Felipe Renan",
  "age": 19,
  "height": 1.75,
  "weight": 83.5,
  "position": 7
}

###